name: Qodana

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v4.2.5
      with: 
        fail-threshold: 0
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
